# Generated by Django 4.2.6 on 2023-10-15 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='winningbid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winning_bid_for', to='auctions.bid'),
        ),
    ]
