# Generated by Django 4.2.6 on 2023-10-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_winningbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replyto',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
