# Generated by Django 4.2.6 on 2023-10-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_comment_date_remove_user_watching_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='earnings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='selling_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sold_num',
            field=models.IntegerField(default=0),
        ),
    ]
