# Generated by Django 4.2.6 on 2023-10-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newalerts',
            field=models.IntegerField(default=0),
        ),
    ]
