# Generated by Django 4.2.6 on 2023-10-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replyto',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imgurl',
            field=models.CharField(default='/static/auctions/product-placeholder.jpg', max_length=200, null=True),
        ),
    ]
